<?php

namespace MyobAdvanced;

use Carbon\Carbon;

/**
 * @method float getAmount()
 * @method self setAmount(float $value)
 * @method string getBranchID()
 * @method self setBranchID(string $value)
 * @method bool getCalculateDiscountsOnImport()
 * @method self setCalculateDiscountsOnImport(bool $value)
 * @method string getCostCode()
 * @method self setCostCode(string $value)
 * @method string getDescription()
 * @method self setDescription(string $value)
 * @method string getDiscountAmount()
 * @method self setDiscountAmount(string $value)
 * @method string getDiscountPercent()
 * @method self setDiscountPercent(string $value)
 * @method string getExpirationDate()
 * @method self setExpirationDate(string $value)
 * @method string getInventoryDocType()
 * @method self setInventoryDocType(string $value)
 * @method string getInventoryID()
 * @method self setInventoryID(string $value)
 * @method string getInventoryRefNbr()
 * @method self setInventoryRefNbr(string $value)
 * @method string getLineNbr()
 * @method self setLineNbr(string $value)
 * @method string getLocation()
 * @method self setLocation(string $value)
 * @method string getLotSerialNbr()
 * @method self setLotSerialNbr(string $value)
 * @method string getManualDiscount()
 * @method self setManualDiscount(string $value)
 * @method string getOrderLineNbr()
 * @method self setOrderLineNbr(string $value)
 * @method string getOrderNbr()
 * @method self setOrderNbr(string $value)
 * @method string getOrderType()
 * @method self setOrderType(string $value)
 * @method string getOrigInvLineNbr()
 * @method self setOrigInvLineNbr(string $value)
 * @method string getOrigInvNbr()
 * @method self setOrigInvNbr(string $value)
 * @method string getOrigInvType()
 * @method self setOrigInvType(string $value)
 * @method string getProjectTask()
 * @method self setProjectTask(string $value)
 * @method string getQty()
 * @method self setQty(string $value)
 * @method string getShipmentNbr()
 * @method self setShipmentNbr(string $value)
 * @method string getSubitem()
 * @method self setSubitem(string $value)
 * @method string getTaxCategory()
 * @method self setTaxCategory(string $value)
 * @method string getTransactionDescr()
 * @method self setTransactionDescr(string $value)
 * @method string getUnitPrice()
 * @method self setUnitPrice(string $value)
 * @method string getUOM()
 * @method self setUOM(string $value)
 * @method string getWarehouseID()
 * @method self setWarehouseID(string $value)
 */
class SalesInvoiceDetail extends AbstractObject
{
}